import { t } from '../../../../../System/I18n/index.js';

export const REFRESH_BUTTON_HTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
  <path d="M23 4v6h-6" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M1 20v-6h6" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15" stroke-linecap="round" stroke-linejoin="round"/>
</svg> ${t('usage.refresh')}`;

export const CLEAR_BUTTON_HTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
  <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6" stroke-linecap="round" stroke-linejoin="round"/>
</svg> ${t('usage.clearData')}`;

const INLINE_STYLE_ID = 'usage-inline-styles';

export function ensureUsageStyles() {
  if (document.getElementById(INLINE_STYLE_ID)) return;
}

export function getHTML(REFRESH_HTML, CLEAR_HTML) {
  return /* html */ `
<main id="main" class="usage-main">
  <div class="usage-scroll">
    <div class="usage-page-header">
      <div class="usage-page-header-copy">
        <h2>
          ${t('usage.title')}
          <span class="agents-tagline-badge">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
              <path d="M3 3v18h18" stroke-linecap="round" />
              <path d="M7 16V10M12 16V6M17 16v-5" stroke-linecap="round" />
            </svg>
            ${t('usage.tagline')}
          </span>
        </h2>
        <p>${t('usage.description')}</p>
      </div>
      <div class="usage-header-actions">
        <div class="usage-range-btns">
          <button class="usage-range-btn active" data-range="today">${t('usage.today')}</button>
          <button class="usage-range-btn" data-range="7">${t('usage.sevenDays')}</button>
          <button class="usage-range-btn" data-range="30">${t('usage.thirtyDays')}</button>
          <button class="usage-range-btn" data-range="all">${t('usage.allTime')}</button>
        </div>
        <button class="usage-refresh-btn" id="refresh-btn">${REFRESH_HTML}</button>
        <button class="usage-clear-btn" id="clear-usage-btn">${CLEAR_HTML}</button>
      </div>
    </div>

    <div class="usage-summary-grid" id="summary-grid"></div>

    <div class="usage-section-full yearly-heatmap-section" id="yearly-heatmap-section">
      <div class="usage-section-header">
        <span class="usage-section-title">AI usage history</span>
        <span class="usage-section-meta" id="yh-meta">daily activity</span>
      </div>
      <div class="yearly-heatmap-outer">
        <div class="yh-main">
          <div class="yh-header-row">
            <div class="yh-day-gutter"></div>
            <div class="yh-month-labels" id="yh-month-labels"></div>
          </div>
          <div class="yh-body-row">
            <div class="yh-day-labels">
              <span></span>
              <span>Mon</span>
              <span></span>
              <span>Wed</span>
              <span></span>
              <span>Fri</span>
              <span></span>
            </div>
            <div class="yh-grid" id="yh-grid"></div>
          </div>
          <div class="yh-legend">
            <span class="yh-legend-text">Less</span>
            <div class="yh-legend-cell" data-level="0"></div>
            <div class="yh-legend-cell" data-level="1"></div>
            <div class="yh-legend-cell" data-level="2"></div>
            <div class="yh-legend-cell" data-level="3"></div>
            <div class="yh-legend-cell" data-level="4"></div>
            <span class="yh-legend-text">More</span>
          </div>
        </div>
        <div class="yh-year-picker" id="yh-year-picker"></div>
      </div>
    </div>

    <div class="usage-section-full" id="insights-section">
      <div class="usage-section-header">
        <span class="usage-section-title">${t('usage.insights')}</span>
        <span class="usage-section-meta">${t('usage.autoGenerated')}</span>
      </div>
      <div id="insights-list"></div>
    </div>

    <div class="usage-sections">
      <div class="usage-section" id="chart-section">
        <div class="usage-section-header">
          <span class="usage-section-title" id="chart-title">${t('usage.dailyUsage')}</span>
          <span class="usage-section-meta" id="chart-meta"></span>
        </div>
        <div class="usage-chart-wrap" id="chart-wrap"></div>
      </div>
      <div class="usage-section" id="provider-section">
        <div class="usage-section-header">
          <span class="usage-section-title">${t('usage.providerBreakdown')}</span>
        </div>
        <div class="provider-grid" id="provider-grid"></div>
      </div>
    </div>

    <div class="usage-two-col">
      <div class="usage-section" id="heatmap-section">
        <div class="usage-section-header">
          <span class="usage-section-title">${t('usage.hourlyActivity')}</span>
          <span class="usage-section-meta">${t('usage.distribution24h')}</span>
        </div>
        <div id="heatmap-wrap"></div>
      </div>
      <div class="usage-section" id="dow-section">
        <div class="usage-section-header">
          <span class="usage-section-title">${t('usage.dayOfWeek')}</span>
          <span class="usage-section-meta">${t('usage.callVolume')}</span>
        </div>
        <div id="dow-wrap"></div>
      </div>
    </div>

    <div class="usage-section-full" id="cost-table-section">
      <div class="usage-section-header">
        <span class="usage-section-title">${t('usage.costByModel')}</span>
        <span class="usage-section-meta">${t('usage.top10')}</span>
      </div>
      <div id="cost-table-body"></div>
    </div>

    <div class="usage-section-full" id="model-section">
      <div class="usage-section-header">
        <span class="usage-section-title">${t('usage.modelBreakdown')}</span>
        <span class="usage-section-meta" id="model-meta"></span>
      </div>
      <div id="model-rows" class="model-rows"></div>
    </div>

    <div class="usage-section-full" id="activity-section">
      <div class="usage-section-header">
        <span class="usage-section-title">${t('usage.recentActivity')}</span>
        <span class="usage-section-meta" id="activity-meta"></span>
      </div>
      <div id="activity-list" class="activity-list"></div>
    </div>
  </div>
</main>

<div class="usage-confirm-overlay" id="confirm-overlay">
  <div class="usage-confirm-box">
    <h3>${t('usage.clearTitle')}</h3>
    <p>${t('usage.clearBody')}</p>
    <div class="usage-confirm-actions">
      <button class="usage-confirm-cancel" id="confirm-cancel">${t('usage.cancel')}</button>
      <button class="usage-confirm-delete" id="confirm-delete">${t('usage.clearConfirm')}</button>
    </div>
  </div>
</div>
`;
}
