import defineFeature from '../Core/DefineFeature.js';
export default defineFeature({
  id: 'free-connectors',
  name: 'Free Connectors',
  connectors: {
    free: [
      {
        id: 'open_meteo',
        name: 'Open-Meteo Weather',
        icon: '☀',
        description: 'Free weather data — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'coingecko',
        name: 'CoinGecko',
        icon: '🪙',
        description: 'Crypto prices and market data — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'exchange_rate',
        name: 'Exchange Rate',
        icon: '💱',
        description: 'Currency exchange rates — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'treasury',
        name: 'US Treasury Rates',
        icon: '🏛',
        description: 'US Treasury yield data — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'wikipedia',
        name: 'Wikipedia',
        icon: '📖',
        description: 'Search and retrieve Wikipedia articles — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'ipgeo',
        name: 'IP Geolocation',
        icon: '📍',
        description: 'IP-based geolocation data — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'funfacts',
        name: 'Fun Facts',
        icon: '🎲',
        description: 'Random fun facts — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'jokeapi',
        name: 'Jokes',
        icon: '😂',
        description: 'Random jokes — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'quotes',
        name: 'Quotes',
        icon: '💬',
        description: 'Inspirational quotes — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'restcountries',
        name: 'Countries',
        icon: '🌍',
        description: 'Country information — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'hackernews',
        name: 'Hacker News',
        icon: '📰',
        description: 'Hacker News top stories — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'cleanuri',
        name: 'URL Shortener',
        icon: '🔗',
        description: 'Shorten URLs — no API key required.',
        noKey: !0,
        defaultState: { enabled: !0 },
      },
      {
        id: 'nasa',
        name: 'NASA',
        icon: '🚀',
        description: 'NASA APIs — free API key required.',
        noKey: !1,
        keyLabel: 'NASA API Key',
        keyPlaceholder: 'DEMO_KEY or your key',
        keyHint: 'Get a free key at api.nasa.gov',
        docsUrl: 'https://api.nasa.gov/',
        defaultState: { enabled: !0, credentials: { apiKey: '' } },
      },
      {
        id: 'fred',
        name: 'FRED Economic Data',
        icon: '📊',
        description: 'Federal Reserve economic data — free API key required.',
        noKey: !1,
        keyLabel: 'FRED API Key',
        keyPlaceholder: 'Your FRED API key',
        keyHint: 'Get a free key at fred.stlouisfed.org/docs/api',
        docsUrl: 'https://fred.stlouisfed.org/docs/API/api_key.html',
        defaultState: { enabled: !0, credentials: { apiKey: '' } },
      },
      {
        id: 'openweathermap',
        name: 'OpenWeatherMap',
        icon: '🌤',
        description: 'Weather data — free API key required.',
        noKey: !1,
        keyLabel: 'OpenWeatherMap API Key',
        keyPlaceholder: 'Your API key',
        keyHint: 'Get a free key at openweathermap.org/api',
        docsUrl: 'https://openweathermap.org/api',
        defaultState: { enabled: !1, credentials: { apiKey: '' } },
      },
      {
        id: 'unsplash',
        name: 'Unsplash',
        icon: '📷',
        description: 'Free high-quality photos — free API key required.',
        noKey: !1,
        keyLabel: 'Unsplash Access Key',
        keyPlaceholder: 'Your access key',
        keyHint: 'Create an app at unsplash.com/developers',
        docsUrl: 'https://unsplash.com/developers',
        defaultState: { enabled: !1, credentials: { apiKey: '' } },
      },
    ],
  },
});
