export const state = {
  messages: [],
  composerAttachments: [],
  isTyping: !1,
  currentChatId: null,
  conversationSummary: '',
  conversationSummaryMessageCount: 0,
  allProviders: [],
  providers: [],
  selectedProvider: null,
  selectedModel: null,
  userName: '',
  systemPrompt: '',
  workspacePath: null,
  activeProject: null,
};
